tigrisdata/tigris-api

- README.md
- server/v1/api.proto
- server/v1/api_openapi.yaml
- server/v1/health.proto
BREAKING CHANGE: repository renamed to tigris-api
> Rename repo to tigris-api

- README.md
- server/v1/api.proto
- server/v1/api_openapi.yaml
- server/v1/health.proto
BREAKING CHANGE: repository renamed to tigris-api
> Alpha release

- openapiv3/annotations.proto
fixed recently https://github.com/google/gnostic/commit/56da86ea7beac6e257e910085b45e7ed201ffeb2#diff-2d98d18c4f6d777a241bf6cb97eeb1dad40aa431724a543d8813c614d661c1ac
> fix: open api package

- .gitignore
Adds a few entries to gitignore list:
- .vscode to exclude Visual Studio Code configuration folders
- .DS_Store for OSX users
> Extend gitignore with convenience options

- server/v1/api.proto
- server/v1/api_openapi.yaml
> feat: added 405 error code

- Makefile
- server/v1/auth.proto
- server/v1/auth_openapi.yaml
To proxy / implement oauth provider.
> feat: Adding auth service

- server/v1/observability.proto
- server/v1/observability_openapi.yaml
Added aggregation and function as user input to control the metrics query.
> feat: Added aggregation and function as user input

- server/v1/auth.proto
- server/v1/auth_openapi.yaml
Tigris will support app based credentials and this PR specifies the API for that feature.
> feat: Added API for application based authentication/authorization

- server/v1/auth.proto
- server/v1/auth_openapi.yaml
> fix: rotateApplicationSecret api

- server/v1/observability.proto
- server/v1/observability_openapi.yaml
- Allow disabling function in query.
- Added an option to query percentile values for timer metrics.
> feat: Allow disabling function in query

- .github/workflows/lint.yaml
- Makefile
- scripts/fix_openapi.sh
- scripts/install_build_deps.sh
- server/v1/admin.proto
- server/v1/admin_openapi.yaml
- server/v1/api.proto
- server/v1/api_openapi.yaml
- server/v1/auth.proto
- server/v1/auth_openapi.yaml
- server/v1/health.proto
- server/v1/health_openapi.yaml
- server/v1/observability.proto
- server/v1/observability_openapi.yaml
- server/v1/user.proto
- server/v1/user_openapi.yaml
* Added OpenAPI linting
* Fixes to pass OpenAPI linting
> Fix genererating OpenAPI for user metadata service

- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/openapi.yaml
The functionality will allow to notify the user only when certain criteria match.
> feat: Support for filters in subscribe

- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/desc.yaml
- server/v1/openapi.yaml
Adding content for status codes, idempotent requests, and limitations. Adding servers so that URL points to preview and localhost.
> fix: Api docs content

- server/v1/api.proto
- server/v1/openapi.yaml
* feat: Limit options for update and delete
* fix: Updated openapi
> Beta release

- scripts/fix_openapi.sh
- server/v1/management.proto
- server/v1/openapi.yaml
- User will be able to control the display name for namespace going forward. Id and Name will be auto generated internally.
> refactor: Enhanced namespace API

- server/v1/management.proto
- server/v1/openapi.yaml
Updated api to get details for all namespaces
> feat: getting details for all namespaces

- server/v1/management.proto
- server/v1/openapi.yaml
Adding optional parameter that enables platform to associate project <> applications.
> feat: Associate apps to projects

- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/openapi.yaml
- Create/Delete/Reset database branches
- Branch is an optional param being passed on to the APIs
`"/v1/projects/{project}/branch/{branch}/create"`
`"/v1/projects/{project}/branch/{branch}/collections/{collection}/documents/insert"`
> feat: Database branching

- server/v1/api.proto
- server/v1/openapi.yaml
Accidentally removed these in prev commit
> fix: Restoring database options in create request

- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/openapi.yaml-e
- One project contains one DB and it will extend with other offerings. 
- DB is replaced by Project in API.
- Event streaming APIs are removed for redesign.
> refactor! [BREAKING] Switching to Project paradigm

- Makefile
- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/cache.proto
- server/v1/openapi.yaml
Initial import of Tigris Cache API.
> feat: Added Cache API

- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/openapi.yaml
refactor!: Application to AppKey
> refactor!: Application to AppKey

- server/v1/openapi.yaml
- server/v1/realtime.proto
1. Add attach and detach
2. Update presence to support actions
3. Added in `ConnectMessage` this is used when a connection is established with the server. We support an optional socket and session id for when a connection is being restored
> feat: Update Realtime api

- scripts/fix_openapi.sh
- server/v1/cache.proto
- server/v1/openapi.yaml
> feat: Added getset cache api

- .github/PULL_REQUEST_TEMPLATE.md
Add a new PR template that will be created for each new PR. This will help us make sure that each PR has more detail about what is going on.
Once this is merged, open a new PR to view the headings in the body of the PR.
None.
> chore: Add PR Template

- server/v1/cache.proto
- server/v1/openapi.yaml
Refactored HTTP path and added `kv` in the path. This allows us to extend the cache APIs further.
N/A
> refactor: Added kv in the HTTP path to allow for extension

- server/v1/cache.proto
- server/v1/openapi.yaml
> docs: Fixed the docs

- Makefile
- server/v1/api.proto
- server/v1/cache.proto
- server/v1/openapi.yaml
- server/v1/search.proto
Adding search index management APIs
> feat: Add search service and index APIs

- server/v1/cache.proto
- server/v1/openapi.yaml
API changes that makes `keys` call to return list of keys in streaming manner.
Implementation will be tested.
> feat: Made keys call serve response in streaming way

- server/v1/openapi.yaml
- server/v1/search.proto
Adding the following APIs for search service:
- Create Document By Id
- Create Documents
- Create Or Replace Documents
- Update Documents
- Delete Documents
- Delete Documents By Query
- Get Documents
> feat: Search crud APIs

- server/v1/api.proto
- server/v1/openapi.yaml
- server/v1/search.proto
> Add filter in list index request params, and add search API

- server/v1/openapi.yaml
- server/v1/search.proto
> feat: Get Index API

- server/v1/api.proto
- server/v1/openapi.yaml
- server/v1/search.proto
> chore: Removing source field from index response and passing it in schema

- server/v1/observability.proto
- server/v1/openapi.yaml
Added branch request payload option to query branch specific time series metrics.
N/A (API only)
> fix: Added branch request parameter to observability API

- server/v1/api.proto
- server/v1/openapi.yaml
- GET `/projects/p1/database/branches` to return a list of branches
> feat: List Branches API

- server/v1/api.proto
- server/v1/observability.proto
- server/v1/openapi.yaml
- server/v1/search.proto
> feat: Add search field match information in response

- server/v1/api.proto
- server/v1/openapi.yaml
- server/v1/search.proto
- Only top level message structs will be different, inside response fields will be same.
- Adding groupedHits in index search response
> Unify search index/collection internal response fields

- server/v1/api.proto
- server/v1/openapi.yaml
- server/v1/search.proto
> Rename GroupedSearchIndexResponse to GroupedSearchHits

- server/v1/openapi.yaml
- server/v1/search.proto
> Add group_by for index search API

- server/v1/api.proto
- server/v1/openapi.yaml
- server/v1/search.proto
Adding vector option for vector search in Search API
> feat: Adding vector option for vector search in Search API

- server/v1/api.proto
- server/v1/openapi.yaml
This will be filled during vector sector.
> feat: Adding vector distance as part of search hit response

- server/v1/api.proto
- server/v1/openapi.yaml
Adds a new explain endpoint
Adds indexes to the describe collection endpoint
The explain endpoint is very basic. I want to add the key ranges and the actual index used. This will be done in a later
PR. I want to do some code refactoring before I add that part.
> feat: add indexing to endpoints

- server/v1/management.proto
- server/v1/openapi.yaml
Added API to get namespace information
N/A
> feat: Added API to get namespace information

- server/v1/management.proto
- server/v1/openapi.yaml
Refactored GetNamespace --> NamespaceInfo
> refactor: API renamed GetNamespace --> NamespaceInfo

- Makefile
- scripts/fix_openapi.sh
- server/v1/openapi.yaml
> Fix openapi spec for recent search APIs

- server/v1/management.proto
- server/v1/openapi.yaml
Added delete namespace management API
> feat: Added delete namespace API

- server/v1/api.proto
- server/v1/openapi.yaml
Adds a new endpoint to do bulk index building
> feat: add build index endpoint

- server/v1/api.proto
- server/v1/openapi.yaml
Add the key ranges for the query and the field used for the query to the explain response
> feat: add range and field to explain

- server/v1/auth.proto
- server/v1/openapi.yaml
Tigris cluster's user management will allow users to invite other users in their org/namespace. This API enables that.
> feat: user invitation API

- server/v1/api.proto
- server/v1/openapi.yaml
- Group by support for collection search
> feat: group by search queries in collection

- server/v1/api.proto
- server/v1/openapi.yaml
> feat: Add count documents API

- server/v1/api.proto
- server/v1/openapi.yaml
> feat: Add branch in the count API

- Makefile
- server/v1/api.proto
- server/v1/billing.proto
- server/v1/management.proto
- server/v1/openapi.yaml
> feat: list invoices api

- server/v1/auth.proto
- server/v1/openapi.yaml
> feat: Added list users API

- server/v1/auth.proto
- server/v1/openapi.yaml
Add namespace name to the user invitation.
N/A
> feat: Add namespace name to the user invitation

- server/v1/api.proto
- server/v1/openapi.yaml
> Add an API to build search index

- .gitignore
- scripts/fix_openapi.sh
- server/v1/api.proto
- server/v1/openapi.yaml
> [API] Batch create collections

- scripts/fix_openapi.sh
- server/v1/openapi.yaml
> fix: Removed duplicate tags for search and billing

- server/v1/auth.proto
- server/v1/openapi.yaml
Added more fields to the invitation responses
N/A
> feat: Added more fields to the invitation responses

- server/v1/api.proto
- server/v1/openapi.yaml
Added API for global app keys.
N/A
> feat: Global app keys api

- server/v1/api.proto
- server/v1/openapi.yaml
> feat: Adding search status in describe collection response

- server/v1/auth.proto
- server/v1/openapi.yaml
Added optional request flag to do dry invitation verification.
N/A
> feat: Dry verification of invitation (without accepting the invitation)

- server/v1/api.proto
- server/v1/openapi.yaml
Add roles to the app keys.
N/A
> feat: Add roles to the app keys

- server/v1/billing.proto
- server/v1/openapi.yaml
- API is not implemented yet
- lint
> fix: Rename params on usage api

- server/v1/api.proto
- server/v1/openapi.yaml
> feat: APIs for API key

- server/v1/api.proto
- server/v1/observability.proto
- server/v1/openapi.yaml
Added API for whoami endpoint. This is mainly for debugging purpose.
N/A
> feat: Added whoami endpoint

- server/v1/api.proto
- server/v1/openapi.yaml
- Setting project metadata when creating a project
- New update project endpoint to update this metadata 
- Unit tests
> feat: Setting and updating project metadata associated with project
